# Generated by Django 4.2.7 on 2023-12-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFutbol', '0002_entrenador_delete_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
    ]
